### PR TITLE
merge brcaswell/Maintenance to ENSL/develop

### PR DESCRIPTION
**Pull request by brcaswell**
addresses CMake and updates gitignore (removes files that are to be ignored)

### CODE REVIEW

**Comment by jirikivaari** [comment]
The CI build fails.

opengl.cpp:19:19: fatal error: GL/gl.h: No such file or directory
688compilation terminated.
689Makefile:39: recipe for target 'opengl.o' failed
690make[1]: *** [opengl.o] Error 1
691make[1]: Leaving directory '/home/travis/build/ENSL/NS/main/source/particles'
692Makefile:145: recipe for target 'particles' failed
693make: *** [particles] Error 2
694The command "cd main/source/linux && make" exited with 2.

**Comment by pierow** [comment]
I don't think we want the makefiles being ignored:
https://github.com/ENSL/NS/pull/39/files#diff-a084b794bc0759e7a6b77810e01874f2R256

**Comment by brcaswell** [comment]
> The CI build fails.
> 
> opengl.cpp:19:19: fatal error: GL/gl.h: No such file or directory
> 688compilation terminated.
> 689Makefile:39: recipe for target 'opengl.o' failed
> 690make[1]: *** [opengl.o] Error 1
> 691make[1]: Leaving directory '/home/travis/build/ENSL/NS/main/source/particles'
> 692Makefile:145: recipe for target 'particles' failed
> 693make: *** [particles] Error 2
> 694The command "cd main/source/linux && make" exited with 2.

Yeah, I should have done a dry-run deletion to see what was impacted by these.  `git rm --cached -n *Makefile*` in bash showed that it was too impactful.

image

**Comment by brcaswell** [comment]
Closing until I can figure how to test this locally

**Pull request closed without merging**
