### PR TITLE
Fixed B_Siege and Heavy models

### PR DESCRIPTION
**Pull request by panyachu**
Fixes:
B_Siege - UV-shifting;
Heavy - welder look animation;
Heavy - foots vertexes assignig.

Siege Before:
B_Siege_Before

Siege After:
B_Siege_After

---

Heavy Welder look animation Before:
heavy_welder_look_before

Heavy Welder look animation After (similar to welder fire animation):
heavy_welder_fire

---

Heavy foots Before:
heavy_foots_before

Heavy foots After:
heavy_foots_after

---

Can see source files in this repository https://github.com/panyachu/ns-assets/tree/develop

### CODE REVIEW

**Comment by pierow** [comment]
Nice work. Thanks again.

What are you using to edit the decompiled files? The siege model blocks bullets in a large area where it shouldn't and I was wondering if that could could be cleaned up but I didn't get around to figuring out model editing.  I imagine it's a bit large because it's one box and there's the unbuilt animation it needs to account for as well.

**Comment by panyachu** [comment]
I use Milkshape 3D, but only for edit meshes and rigging.
Realy, I noticed this behavior too.
But I don't think this is directly related to the model, perhaps the program code creates this box.
Because hitboxes are created for each joint individually:
B_Siege_hitboxes

The source .qc file contains the following lines:
```
$cbox 0 0 0 0 0 0
$bbox 0 0 0 0 0 0
```
This means that the BBOX is automatically generated around the model.

So this is not the reason, i think.

**Comment by panyachu** [comment]
I can view BBOX only in HLMV v 2.0 for Source engine.
And this is how it looks:
B_Siege_BBOX

**Comment by panyachu** [comment]
I realized what my mistake was.
But this only affects the blocking effect of bullets, not the size of the area.
The decompiled .qc files contained the following lines:
```
$cbox 0 0 0 0 0 0
$bbox 0 0 0 0 0 0
```
But decompiled .qc files from Milkshape 3D do not contain these lines.
The presence of these lines creates sparks around the model, as if from an invisible metal wall.

I will create another pull request with fixing this behavior.

**Comment by pierow** [comment]
Sorry, I wasn't specific enough with what I said.  What I was referring to is not an issue with your edit.  It's something that's been in the game for a long time.  What I'm talking about is likely just caused by the hitboxes for the tripod covering a lot of empty space.  I assume there's no way to rotate the boxes so the original devs did what they could. I think just using 3 instead of 2 boxes for the legs in a pyramid shape would probably help since the main culprit is the second box from the bottom. Can those be edited in milkshape?  I could also just try text editing the qc file and looking at the results in HLMV.

Good catch with the cbox and bbox issue though.  I haven't tested the new models yet.

**Comment by panyachu** [comment]
I thought it was about blocking bullets above the model.
I checked and found out that the bullets are blocked at a great distance above the model.
Hitboxes are set in the .qc file, where you can specify several of them at once per joint.

**Comment by pierow** [comment]
I've fixed the bullet sparks issue and have redone the hitboxes as well to better match the model. It will be in a coming update. You were right about that cbox and bbox entries causing it.

There is an additional issue with the hitboxes that rotate being hittable in their original location as well as the rotated one.  I'll have to investigate this later and see if it's fixable.  It's possible this is done on every animated model because it's hard to sync animation states with the server.

**Pull request merged**
