### PR TITLE
Features and fixes for v3.3b1

### LINKED ISSUE #13: commander arrow keys
it was possible at version 3.2 to move the commander view with the cursor keys. Doesn't work now.

### LINKED ISSUE #45: Chatbox eats inputs occasionally
Chatbox eats inputs occasionally. I think its SDL related.

### LINKED ISSUE #58: Buildings nobuild radius needs to be made spherical
This is an old NS bug that was introduced when buildings had radial build limits to prevent spamming walls of them and griefing the opposing team.

https://steamuserimages-a.akamaihd.net/ugc/1017194390692209216/C57C015A16B72D1DA79A8B14CE5542D497EA6088/
https://steamuserimages-a.akamaihd.net/ugc/1017194390692239931/866DDEDECB0E2BE8D5623E824ED3B22169E705F1/

Like with the observatory bug fixed some years ago in 3.2.1, the building radius is a cylinder which extends to the absolute mins/maxes of the world (+/-4096). This prevents buildings placed above or below other buildings, even when they're significant distances apart. This creates problems on "stacked" areas or stacked maps (like silo maps) where entire areas can be blocked from construction by buildings placed above or below them at any distance.

All buildings in the game have a nobuild radius around them, including resource nozzles.

### LINKED ISSUE #59: Structures with negative Z coords are bugged when clicked
If parts of map have negative Z coordinates, clicking a structure can deselect it or select antoher structure. Make sure all parts of the map have positive Z coordinate..

### LINKED ISSUE #68: +speed (silent walk) inconsistencies
Since v3.2.1a, using the +speed command to walk silently has been bugged to be slower than normal for most users.  This is currently band-aid fixed by editing the associated movespeedkey values for each player class by 2.5x to return the resulting speeds to their intended value.

The problem with this fix, apart from not solving the root cause, is one user has reported that they don't experience this issue when running v3.2.1a, but they haven't tested the new builds to see how the edited values affect them.  The only reported difference in their setup from most others was that they were running windows 7 as well as in compatibility mode for winXP SP3.  From testing on my end in windows 10 with and without compatibility mode it is bugged and needs the edited values for normal play.

A while back puzl updated the cvar locking code for movespeedkey, but reverting those changes had no affect on my end.

### LINKED ISSUE #71: No game version consistency check
A consistency check from the server to each client should be done to verify everyone is playing the same version of the game.  Users on a mismatched version, old client on a new server or vice versa, is fairly common and the amount of bugs that result is only going to grow.  Malicious clients are also a possibility.

So far I've tried adding entries for ns.dll/so/dylib akin to this:
https://github.com/ENSL/NS/blob/2fb18b989f8ba369a94a3a7a80bcc14bdd1e42d9/main/source/dlls/client.cpp#L1227
defined here:
https://github.com/ENSL/NS/blob/2fb18b989f8ba369a94a3a7a80bcc14bdd1e42d9/main/source/dlls/enginecallback.h#L91-L98

This has had no affect in my testing, but I think it's likely something small preventing it from working.

### LINKED ISSUE #73: Weapons floating in air
Same issue on UWE repo: https://github.com/unknownworlds/NS/issues/3

When a player dies, the weapons dropped tends to get stuck on each other and float in the air, making it so other players can't pick them up. This seems to happen more on high tick rate servers.  Recreation for typical occurrence is to `kill` in console after equipping an HMG and welder.  This can also be recreated by dropping weapons in quick succession while looking up in the air to make them collide.

A plugin exists that searches around players when they die and uses `EF_DropToFloor`, fixing the most problematic occurrences.

### LINKED ISSUE #77: ns version does not match
Hi, I have installed the latest release ns_v322_full.zip using linux ubuntu 16.04, metamod 1.21p and hlds build 8308

The problem is that when I raise the server it appears in favorites as the game name "NS 3.2.0" when in fact I have installed "NS 3.2.2" or some servers appear "NS 3.2.1"

Any solution?

Thanks!

### LINKED ISSUE #81: Shotgun reload bugs
Several shotgun bugs.

- [ ] Sometimes firing animation does not play
- [ ] Reloading forever
- [ ] Shooting while reloading causes it to shoot randomly, sometimes twice fast after a pause.

### LINKED ISSUE #88: Onos devour gets displayed as Babblers
Description:
--
if you turn weapon fast switch off the weapon_devour has the babblers symbol (left top corner of the image)

Tested with:
--
Client: 3.2.2 Windows
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 19:53:27 Aug  3 2020 (8684)

Server: 3.2.1 Linux (current ENSL UK server) and
version :  48/1.1.2.2/Stdio 8308 secure  (70)

Server: 3.2.2 Windows
version :  48/1.1.2.2 8684 secure  (70)

How to reproduce:
--
1. Turn weapon fastswitch off
2. evolve to onos with cheats 0 or 1. 
3. choose weaponslot 2

### PR DESCRIPTION
**Pull request by pierow**
- Shotgun rework. Previously inconsistent shooting during reloads and desynced animations with server. Fixes https://github.com/ENSL/NS/issues/81
   - Shotgun reload can now be interrupted with a pump animation
   - Changed pellets 10 -> 17 and damage 17-> 10 to reduce inconsistency
- Networked ammo and shotgun reload state
- `mp_consistency` changed to 0 = don't check files, 1 = check game dlls and some cheating prone files that don't typically get user customized like footsteps and map textures, 2 = more stringent check for competitive play (previously 1)
   - Client and server dll consistency checks added. Resolves https://github.com/ENSL/NS/issues/71
   - Added additional player sound and map texture checks
- Backwards compatibility check for v3.2 servers to prevent prediction errors
- Players can change lifeform and use popupmenu in pregame warmup
- Fixed guns getting stuck in the air. Fixes https://github.com/ENSL/NS/issues/73
- Reverted max speed to not be client cvar adjustable, fixing walk speed issues. Fixes https://github.com/ENSL/NS/issues/68
- Added `cl_mutemenu` for players accidentally clicking on the scoreboard and going into squelch mode. Partial fix for https://github.com/ENSL/NS/issues/46
- Removed `default_fov` as it did nothing but change sensitivity
- Fixed commander view scrolling keybinds. Fixes https://github.com/ENSL/NS/issues/13
- `cl_showspeed` no longer requires sv_cheats 1 and is usable in the readyroom and spectate.
- Fixes https://github.com/ENSL/NS/issues/45 Credit to Bacsu.
- Fixes https://github.com/ENSL/NS/issues/58 Credit to AlienBird.
- Fixes https://github.com/ENSL/NS/issues/59 Credit to AlienBird.
- Recycling now accounts for upgrade costs. Credit to AlienBird.
- `cl_ambientsound` now scales ambient sound volume instead of on/off. Limiting to 1x because people have `cl_ambientsound 2` in their configs from last patch.
- Fixes https://github.com/ENSL/NS/issues/77
- Added `nsversion` client cvar for clients to check their version
- marineofficial.cfg and alienofficial.cfg get automatically executed when joining the respective teams or respawning on them
- Alien health/armor no longer inset on the screen
- Per-weapon configs added that are executed when swapping to each weapon
- Mouse accel is no longer default to on when raw input is off
   - Old `-noforcemaccel -noforcemspd` parameters removed as they no longer functioned as intended due to windows updates
   - Added `-forcemaccel` for players that want the old acceleration
   - `-noforcemparms` still functions the same - it retains mouse acceleration parameters from the windows desktop
- HUD sprites are now correctly scaled for screen resolutions more than 1600 pixels wide. Fixes tiny legacy crosshairs and fixes https://github.com/ENSL/NS/issues/88
- The windows cursor no longer shows over the in game sprite cursor when on the popupmenu.
- cl_cross circle thickness and outline added credit to execut4ble. NS inner outline functionality added to it.
- Lerks no longer stick to the ground if they touch it when gliding.

### CODE REVIEW

**Comment by EterniumDev** [comment]
cl_showspeed does not work yet in spectator or ready room
I've fixed ready room cl_showspeed but not yet spectator
I guess that will have to wait until v324

**Comment by pierow** [comment]
> cl_showspeed does not work yet in spectator or ready room
> I've fixed ready room cl_showspeed but not yet spectator
> I guess that will have to wait until v324

Thanks for letting me know. Should be fixed now.

**Comment by pierow** [comment]
> 
> 
> Pregame lifeforms doesn't work at combat map.

Fixed, thanks.

**Comment by pierow** [comment]
Messed up the last commit trying to resolve conflicts.  Will fix in a bit.

**Pull request merged**
